### ISSUE TITLE
[Demo]第一期实现内容：集群资源规划

### ISSUE THREAD

**Issue by TheBeatles1994** [alibaba/open-simulator#19]
演示内容：

> deadline：2021年11月15号（周一）

- 模拟拉起 Kubernetes 集群：节点规格（CPU、内存、硬盘）、节点数通过Yaml文件指定。集群包含如下节点：
  - master节点
  - 普通worker节点
  - 专用节点
- 准备用户的 Helm Chart 文件（可以是 web server / nginx / mysql / redis 类应用）
  - Chart 中包含 K8s 标准的 [Workload](https://kubernetes.io/docs/concepts/workloads/) 文件，Workload中指定了不同的资源配额、调度规则（亲和、反亲和特性，包含应用之间以及应用-节点间亲和规则）、副本数
  - Chart 中包含自定义 CR 资源
  - 有多个 Chart 文件，Chart 之间有依赖关系
- Open-Simulator 读取 Helm Chart，并给出如下结果：
  - 当前模拟集群是否可以一次性部署上述所有应用；若不满足，给出推荐的集群规模。
  - 显示应用部署之后的集群资源分配率
  - 显示应用部署之后的集群调度拓扑情况

**Comment by VinceCui** [comment]
MR Sun， NewBEE~~~

**Comment by TheBeatles1994** [comment]
done
