### ISSUE TITLE
与社区项目区别

### ISSUE THREAD

**Issue by huiwq1990** [alibaba/open-simulator#68]
## Question

社区开源两个项目：https://github.com/kubernetes-sigs/cluster-capacity https://github.com/kubernetes-sigs/kube-scheduler-simulator
open-simulator跟他们有些功能是相似的，会考虑跟他们协同吗？

**Comment by TheBeatles1994** [comment]
[cluster-capacity](https://github.com/kubernetes-sigs/cluster-capacity) 这个项目也是预测集群容量是否可以部署应用资源，局限性在于仅支持判断某个指定 [podspec](https://github.com/kubernetes-sigs/cluster-capacity#demonstration) 的可部署副本数，这个对于应用的容量规划远远不够。open-simulator 支持部署任意数量的 workload，其中也考虑了应用副本数、应用申请资源（cpu、内存等）、应用间复杂的亲和性/反亲和性等，同时也在集群规模or拓扑架构不满足应用部署时，支持添加虚拟节点模仿实际的物理节点以满足部署要求。
[kube-scheduler-simulator](https://github.com/kubernetes-sigs/kube-scheduler-simulator) 是一个很好的项目，其目的在于获取调度器中各个阶段（filter、score等阶段）的调度结果（这些信息从原生调度器中无法获取），项目要解决的问题并不在于容量规划。open-simulator 要解决集群的资源规划问题，不止有应用的容量规划，还有碎片整理、集群交付规划等一系列功能。
